import json, ast, os

def md(src): return {'cell_type':'markdown','metadata':{},'source':src}
def code(src): return {'cell_type':'code','execution_count':None,'metadata':{},'outputs':[],'source':src}

cells = []

cells.append(md(
"# 03_instrument_diagnostics_and_macro_merge.ipynb\n"
"## Does Δ²CGI work as an instrument? Full validation.\n\n"
"This notebook answers the one question that determines whether the index you built is useful:\n"
"**does Δ²CGI have enough first-stage power to instrument lpri?**\n\n"
"It also merges the composite GPR panel with the Saadaoui estimation dataset (df_extended.csv),\n"
"producing the master panel ready for DML and LP-IV in the next notebook.\n\n"
"**Run every cell in order. The output of Cell 6 (first-stage F) is the key diagnostic.**\n"
))

cells.append(md("## Cell 1 — Imports & Paths\n"))
cells.append(code(
"from pathlib import Path\n"
"import warnings, json\n"
"import numpy as np\n"
"import pandas as pd\n"
"import matplotlib.pyplot as plt\n"
"import matplotlib.ticker as mticker\n"
"from scipy import stats\n"
"import statsmodels.api as sm\n"
"from statsmodels.tools.tools import add_constant\n"
"from statsmodels.tsa.stattools import grangercausalitytests\n"
"from linearmodels.iv import IV2SLS\n\n"
"warnings.filterwarnings('ignore')\n"
"np.random.seed(42)\n"
"plt.rcParams.update({'figure.dpi':120,'figure.facecolor':'white',\n"
"                     'axes.spines.top':False,'axes.spines.right':False})\n\n"
"ROOT     = Path(r'C:\\Users\\HP\\Desktop\\replication+contribution')\n"
"FINAL    = ROOT / 'data' / 'final'\n"
"OUT_03C  = ROOT / 'outputs' / '03c'\n"
"OUT_DIAG = ROOT / 'outputs' / '04_diagnostics'\n"
"OUT_DIAG.mkdir(parents=True, exist_ok=True)\n\n"
"print('Paths set.')\n"
"print(f'Composite panel exists: {(OUT_03C / \"composite_gpr_panel.parquet\").exists()}')\n"
"print(f'df_extended exists:     {(FINAL / \"df_extended.csv\").exists()}')\n"
))

cells.append(md(
"## Cell 2 — Load the composite GPR panel\n\n"
"Load the parquet output from 03_again.ipynb. We only need CHN-USA for the main instrument\n"
"diagnostics (since df_extended.csv is the CHN-USA estimation dataset from Saadaoui).\n"
))
cells.append(code(
"composite = pd.read_parquet(OUT_03C / 'composite_gpr_panel.parquet')\n"
"composite['date'] = pd.to_datetime(composite['date'])\n"
"composite = composite.sort_values(['dyad','date']).reset_index(drop=True)\n\n"
"print(f'Composite panel: {composite.shape}')\n"
"print(f'Dyads: {sorted(composite[\"dyad\"].unique())}')\n"
"print(f'Date range: {composite[\"date\"].min().date()} to {composite[\"date\"].max().date()}')\n"
"print()\n\n"
"# CHN-USA slice\n"
"usa = composite[composite['dyad']=='CHN-USA'].copy()\n"
"usa['month'] = usa['date'].dt.to_period('M').dt.to_timestamp()\n"
"usa = usa.set_index('month').sort_index()\n\n"
"print('CHN-USA composite GPR summary:')\n"
"key_cols = [c for c in ['composite_gpr','delta2_cgi','delta1_cgi',\n"
"                         'gdelt_score_z','icews_score_z','sentiment_score_z']\n"
"            if c in usa.columns]\n"
"print(usa[key_cols].describe().round(4))\n"
))

cells.append(md(
"## Cell 3 — Load df_extended.csv (Saadaoui estimation dataset)\n\n"
"This is the dataset from notebooks 01-05: 385 observations, CHN-USA, 1990-2022.\n"
"We merge the composite GPR features onto it by date.\n"
))
cells.append(code(
"df_ext = pd.read_csv(FINAL / 'df_extended.csv', index_col=0, parse_dates=True)\n"
"df_ext.index = pd.to_datetime(df_ext.index).to_period('M').to_timestamp()\n"
"df_ext = df_ext.sort_index()\n\n"
"with open(FINAL / 'variable_roles.json') as f:\n"
"    roles = json.load(f)\n"
"_DROP = {'baa10y','tb3ms','l2lwip'}\n"
"CONTROLS = [c for c in roles['controls_core']+roles['controls_macro']+roles['controls_geopol']\n"
"            if c not in _DROP and c in df_ext.columns]\n\n"
"print(f'df_extended: {df_ext.shape}')\n"
"print(f'Date: {df_ext.index.min().date()} to {df_ext.index.max().date()}')\n"
"print(f'Controls ({len(CONTROLS)}): {CONTROLS}')\n"
"print()\n\n"
"# Merge composite GPR onto df_extended\n"
"gpr_cols = [c for c in ['composite_gpr','delta2_cgi','delta1_cgi',\n"
"                          'gdelt_score_z','icews_score_z','swb_score_z',\n"
"                          'nyt_score_z','sentiment_score_z']\n"
"            if c in usa.columns]\n"
"m = df_ext.join(usa[gpr_cols], how='left')\n\n"
"print(f'Merged dataset: {m.shape}')\n"
"print()\n"
"print('GPR feature coverage in estimation sample:')\n"
"for col in gpr_cols:\n"
"    n_nonull = m[col].notna().sum()\n"
"    pct = n_nonull / len(m) * 100\n"
"    print(f'  {col:25s}: {n_nonull}/{len(m)} ({pct:.1f}%)')\n"
))

cells.append(md(
"## Cell 4 — Visual Validation: Does the index spike at known events?\n\n"
"Before any regression, check qualitatively: does Δ²CGI show large values at\n"
"months when US-China relations sharply changed? If the index is working, you\n"
"should see notable spikes at: 1996-03 (Taiwan Strait), 1999-05 (Belgrade bombing),\n"
"2001-04 (EP-3), 2018-03 (trade war), 2020-01 (COVID).\n\n"
"This is the same validation Bondarenko et al. (2026) do for their euro area index.\n"
))
cells.append(code(
"fig, axes = plt.subplots(3, 1, figsize=(13, 9), sharex=True)\n\n"
"EVENTS = {\n"
"    '1996-03': 'Taiwan\\nStrait', '1999-05': 'Belgrade',\n"
"    '2001-04': 'EP-3', '2018-03': 'Trade\\nwar',\n"
"    '2019-05': 'Huawei', '2020-03': 'COVID',\n"
"}\n\n"
"# Panel 1: Composite GPR level\n"
"ax = axes[0]\n"
"s = m['composite_gpr'].dropna()\n"
"ax.plot(s.index, s, color='#2C3E50', lw=1.3)\n"
"q75 = s.quantile(0.75)\n"
"ax.fill_between(s.index, s, q75, where=s > q75, alpha=0.25, color='#C0392B')\n"
"ax.axhline(q75, color='#C0392B', ls='--', lw=0.8, alpha=0.7)\n"
"ax.set_ylabel('Composite GPR\\n(z-score)')\n"
"ax.set_title('CHN-USA Composite GPR: Does it spike at known events?', fontweight='bold', fontsize=9)\n"
"for d, label in EVENTS.items():\n"
"    try:\n"
"        ax.axvline(pd.Timestamp(d), color='grey', ls=':', lw=0.9, alpha=0.7)\n"
"        ax.text(pd.Timestamp(d), ax.get_ylim()[1] * 0.88, label,\n"
"                fontsize=7, ha='center', color='#2C3E50')\n"
"    except: pass\n\n"
"# Panel 2: Δ²CGI (the instrument)\n"
"ax = axes[1]\n"
"if 'delta2_cgi' in m.columns:\n"
"    d2 = m['delta2_cgi'].dropna()\n"
"    pos = d2.clip(lower=0); neg = d2.clip(upper=0)\n"
"    ax.bar(d2.index, pos, color='#27AE60', width=25, alpha=0.8, label='Positive Δ²CGI')\n"
"    ax.bar(d2.index, neg, color='#C0392B', width=25, alpha=0.8, label='Negative Δ²CGI')\n"
"    ax.axhline(0, color='black', lw=0.6)\n"
"    ax.set_ylabel('Δ²CGI\\n(instrument)')\n"
"    ax.legend(fontsize=8)\n\n"
"# Panel 3: Δ²PRI (Saadaoui's instrument — for comparison)\n"
"ax = axes[2]\n"
"if 'd2pri' in m.columns:\n"
"    d2p = m['d2pri'].dropna()\n"
"    pos = d2p.clip(lower=0); neg = d2p.clip(upper=0)\n"
"    ax.bar(d2p.index, pos, color='#2980B9', width=25, alpha=0.8, label='Positive Δ²PRI')\n"
"    ax.bar(d2p.index, neg, color='#8E44AD', width=25, alpha=0.8, label='Negative Δ²PRI')\n"
"    ax.axhline(0, color='black', lw=0.6)\n"
"    ax.set_ylabel('Δ²PRI\\n(Saadaoui)')\n"
"    ax.legend(fontsize=8)\n"
"ax.set_xlabel('Date')\n\n"
"plt.tight_layout()\n"
"plt.savefig(OUT_DIAG / 'instrument_comparison_timeseries.png', dpi=150, bbox_inches='tight')\n"
"plt.show()\n"
"print('Saved: instrument_comparison_timeseries.png')\n\n"
"# Correlation between Δ²CGI and Δ²PRI\n"
"if 'd2pri' in m.columns and 'delta2_cgi' in m.columns:\n"
"    sub = m[['d2pri','delta2_cgi']].dropna()\n"
"    r, p = stats.pearsonr(sub['d2pri'], sub['delta2_cgi'])\n"
"    print(f'Correlation Δ²PRI vs Δ²CGI: r={r:+.4f}, p={p:.4f}')\n"
"    print('Expected: LOW (|r| < 0.3) — they capture complementary dimensions')\n"
"    if abs(r) < 0.3:\n"
"        print('CONFIRMED: The two instruments are complementary, not redundant.')\n"
"    else:\n"
"        print('NOTE: Moderate correlation — the instruments share some signal.')\n"
))

cells.append(md(
"## Cell 5 — Benchmark Correlations\n\n"
"Check whether the composite GPR level correlates in the expected direction with:\n"
"- **lpri (PRI level):** Should be NEGATIVE — higher GPR stress = lower PRI (worse relationship)\n"
"- **lwti (log WTI):** Should be weakly POSITIVE — geopolitical stress raises oil prices\n"
"- **d2pri (Saadaoui instrument):** Should be LOW — complementary, not identical\n"
"- **Caldara-Iacoviello GPR (gpr_chn_l1):** Should be POSITIVE — same concept, different measurement\n"
))
cells.append(code(
"print('BENCHMARK CORRELATIONS (CHN-USA, full sample)')\n"
"print('='*65)\n"
"print(f'{\"Pair\":45s} {\"r\":>8} {\"p\":>8} {\"n\":>6} {\"Expected\"}')\n"
"print('-'*65)\n\n"
"benchmarks = [\n"
"    ('composite_gpr', 'lpri',       'GPR vs PRI level',          'negative'),\n"
"    ('composite_gpr', 'lwti',       'GPR vs log WTI',             'weakly +'),\n"
"    ('composite_gpr', 'd2pri',      'GPR vs Δ²PRI',               'low |r|'),\n"
"    ('composite_gpr', 'gpr_chn_l1', 'GPR vs Caldara China GPR',   'positive'),\n"
"    ('composite_gpr', 'gpr_usa_l1', 'GPR vs Caldara USA GPR',     'positive'),\n"
"    ('composite_gpr', 'vix',        'GPR vs VIX',                 'positive'),\n"
"    ('delta2_cgi',    'd2pri',      'Δ²CGI vs Δ²PRI',             'low |r|'),\n"
"    ('delta2_cgi',    'lwti',       'Δ²CGI vs log WTI (raw)',      'any'),\n"
"]\n\n"
"corr_results = []\n"
"for c1, c2, label, expected in benchmarks:\n"
"    if c1 not in m.columns or c2 not in m.columns: continue\n"
"    sub = m[[c1,c2]].dropna()\n"
"    if len(sub) < 10: continue\n"
"    r, p = stats.pearsonr(sub[c1], sub[c2])\n"
"    sig = '✓' if p < 0.10 else ''\n"
"    print(f'{label:45s} {r:>+8.4f} {p:>8.4f} {len(sub):>6} {expected} {sig}')\n"
"    corr_results.append({'pair':label,'r':r,'p':p,'n':len(sub),'expected':expected})\n\n"
"pd.DataFrame(corr_results).to_csv(OUT_DIAG / 'benchmark_correlations.csv', index=False)\n"
"print('\\nSaved: benchmark_correlations.csv')\n"
))

cells.append(md(
"## Cell 6 — THE KEY TEST: First-Stage F-Statistic\n\n"
"**This cell tells you whether Δ²CGI is a valid instrument.**\n\n"
"The test: regress lpri (endogenous treatment) on Δ²CGI + controls.\n"
"If F > 10 (Staiger-Stock 1997): usable instrument.\n"
"If F > 16.4 (Stock-Yogo 5% size): strong instrument.\n"
"If F > 104 (Montiel-Olea-Pflueger): robust strong instrument.\n\n"
"We compare against d²PRI (F ≈ 178-244) as the benchmark.\n\n"
"**If Δ²CGI F < 10:** it cannot replace d²PRI as the sole instrument,\n"
"but can be used as an over-identification check or additional control.\n"
"This is an honest finding — it shows narrative diplomatic coding captures\n"
"a precision that automated event classification cannot replicate.\n\n"
"**If Δ²CGI F > 10:** it is a valid alternative instrument. Run the LP-IV\n"
"with Δ²CGI and compare the IRF to Saadaoui's. Agreement = robustness.\n"
))
cells.append(code(
"def _prune(df_sub, cols):\n"
"    keep, seen = [], {}\n"
"    for c in cols:\n"
"        if c not in df_sub.columns: continue\n"
"        s = df_sub[c]\n"
"        if s.std() < 1e-10: continue\n"
"        key = tuple(((s - s.mean()) / s.std()).round(6))\n"
"        if key in seen: continue\n"
"        seen[key] = c; keep.append(c)\n"
"    return keep\n\n"
"def first_stage_f(data, instrument, controls, treatment='lpri', outcome='lwti'):\n"
"    w = data.copy()\n"
"    for l in range(1, 4): w[f'Ly{l}'] = w[outcome].shift(l)\n"
"    for l in range(1, 3): w[f'Lt{l}'] = w[treatment].shift(l)\n"
"    lags = [f'Ly{l}' for l in range(1,4)] + [f'Lt{l}' for l in range(1,3)]\n"
"    cols = [treatment, instrument] + lags + controls\n"
"    sub = w[[c for c in cols if c in w.columns]].dropna()\n"
"    if len(sub) < 30: return float('nan'), 0\n"
"    cl = _prune(sub, lags + controls)\n"
"    X = add_constant(sub[[instrument] + cl], has_constant='add')\n"
"    fit = sm.OLS(sub[treatment], X).fit(cov_type='HC1')\n"
"    try: f = float(fit.f_test(f'{instrument}=0').fvalue)\n"
"    except: f = float('nan')\n"
"    t = fit.tvalues.get(instrument, float('nan'))\n"
"    return f, len(sub), t\n\n"
"print('FIRST-STAGE F-STATISTIC: ALL INSTRUMENTS')\n"
"print('='*70)\n"
"print(f'{\"Instrument\":35s} {\"F-stat\":>10} {\"t-stat\":>8} {\"n\":>6} {\"Verdict\"}')\n"
"print('-'*70)\n\n"
"instruments_to_test = [\n"
"    ('d2pri',        'd²PRI (Saadaoui — BENCHMARK)'),\n"
"    ('delta2_cgi',   'Δ²CGI composite (your constructed)'),\n"
"    ('delta1_cgi',   'Δ¹CGI (first difference)'),\n"
"    ('gdelt_score_z','GDELT z-score only'),\n"
"    ('icews_score_z','ICEWS z-score only'),\n"
"    ('sentiment_score_z', 'FinBERT sentiment z-score'),\n"
"]\n\n"
"f_results = {}\n"
"for instr, label in instruments_to_test:\n"
"    if instr not in m.columns:\n"
"        print(f'{label:35s} NOT IN DATA')\n"
"        continue\n"
"    result = first_stage_f(m, instr, CONTROLS)\n"
"    f, n, t = result if len(result) == 3 else (*result, float('nan'))\n"
"    thresh = ('F>104 ✓✓' if f > 104 else\n"
"              ('F>16.4 ✓' if f > 16.4 else\n"
"               ('F>10 usable' if f > 10 else\n"
"                ('near (5-10)' if f > 5 else 'WEAK'))))\n"
"    print(f'{label:35s} {f:>10.2f} {t:>8.2f} {n:>6}  {thresh}')\n"
"    f_results[instr] = {'f':f,'t':t,'n':n,'label':label}\n\n"
"pd.DataFrame(f_results).T.to_csv(OUT_DIAG / 'first_stage_f_stats.csv')\n"
"print('\\nSaved: first_stage_f_stats.csv')\n\n"
"# Interpretation\n"
"print()\n"
"print('INTERPRETATION:')\n"
"f_cgi = f_results.get('delta2_cgi', {}).get('f', 0)\n"
"f_pri = f_results.get('d2pri', {}).get('f', 0)\n"
"if f_cgi >= 10:\n"
"    print(f'  Δ²CGI reaches the weak-instrument threshold (F={f_cgi:.1f}).')\n"
"    print(f'  It is {f_pri/f_cgi:.1f}× weaker than d²PRI but valid as alternative instrument.')\n"
"    print(f'  NEXT: Run LP-IV with Δ²CGI and compare IRF to Saadaoui (robustness check).')\n"
"else:\n"
"    print(f'  Δ²CGI F={f_cgi:.2f} — below the weak-instrument threshold.')\n"
"    print(f'  This is a FINDING: narrative diplomatic coding (PRI) captures a precision')\n"
"    print(f'  that automated news-event classification cannot replicate.')\n"
"    print(f'  NEXT: Use Δ²CGI as (a) over-identification check with d²PRI, or')\n"
"    print(f'        (b) additional control in the DML nuisance function.')\n"
))

cells.append(md(
"## Cell 7 — Exogeneity Test: Does Δ²CGI predict WTI without going through PRI?\n\n"
"The exclusion restriction requires that Δ²CGI only affects WTI through its effect on\n"
"bilateral relations (lpri). If Δ²CGI directly predicts future WTI (Granger-causes it)\n"
"independently of lpri, the instrument is endogenous.\n\n"
"Test: Granger non-causality of Δ²CGI on lwti conditional on controls.\n"
"Expected result: p > 0.10 (fail to reject non-causality = instrument is exogenous).\n"
))
cells.append(code(
"print('EXOGENEITY TEST: Granger non-causality of Δ²CGI on lwti')\n"
"print('='*60)\n\n"
"if 'delta2_cgi' in m.columns:\n"
"    # Simple lead-lag test: does delta2_cgi at t predict lwti at t+1,t+2,t+3?\n"
"    print('Lead-lag regression: lwti_{t+h} ~ delta2_cgi_t + controls')\n"
"    print(f'{\"h\":>4} {\"Δ²CGI coef\":>12} {\"t-stat\":>8} {\"p-val\":>8} {\"Exogenous?\"}')\n"
"    print('-'*55)\n"
"    exog_results = []\n"
"    for h in [1, 2, 3, 6, 12]:\n"
"        w = m.copy()\n"
"        w['_y_lead'] = w['lwti'].shift(-h)\n"
"        for l in range(1,4): w[f'Ly{l}'] = w['lwti'].shift(l)\n"
"        lags = [f'Ly{l}' for l in range(1,4)]\n"
"        cols = ['_y_lead','delta2_cgi'] + lags + CONTROLS\n"
"        sub = w[[c for c in cols if c in w.columns]].dropna()\n"
"        if len(sub) < 30: continue\n"
"        cl = _prune(sub, lags + CONTROLS)\n"
"        X = add_constant(sub[['delta2_cgi'] + cl], has_constant='add')\n"
"        fit = sm.OLS(sub['_y_lead'], X).fit(cov_type='HAC', cov_kwds={'maxlags': h+1})\n"
"        coef = fit.params.get('delta2_cgi', float('nan'))\n"
"        tval = fit.tvalues.get('delta2_cgi', float('nan'))\n"
"        pval = fit.pvalues.get('delta2_cgi', float('nan'))\n"
"        exog = 'OK (p>0.10)' if pval > 0.10 else 'CAUTION (p<0.10)'\n"
"        print(f'{h:>4} {coef:>+12.4f} {tval:>8.2f} {pval:>8.4f}  {exog}')\n"
"        exog_results.append({'h':h,'coef':coef,'t':tval,'p':pval})\n"
"    pd.DataFrame(exog_results).to_csv(OUT_DIAG / 'exogeneity_test.csv', index=False)\n"
"    print('\\nSaved: exogeneity_test.csv')\n"
"    print()\n"
"    n_sig = sum(1 for r in exog_results if r['p'] < 0.10)\n"
"    if n_sig == 0:\n"
"        print('RESULT: Δ²CGI does not directly predict future WTI at any horizon.')\n"
"        print('Exclusion restriction is supported.')\n"
"    else:\n"
"        print(f'RESULT: Δ²CGI predicts WTI directly at {n_sig}/5 horizons.')\n"
"        print('This weakens the exogeneity claim. Report honestly in limitations.')\n"
))

cells.append(md(
"## Cell 8 — LP-IV with Δ²CGI: Compare IRF to Saadaoui\n\n"
"If the first-stage F in Cell 6 was ≥ 10, run LP-IV using Δ²CGI as instrument.\n"
"Compare the IRF to Saadaoui's d²PRI baseline.\n"
"Convergence = the causal channel is robust to how geopolitical stress is measured.\n"
"Divergence = the two instruments identify different margins of the treatment.\n\n"
"If F < 10, this cell still runs but CIs will be wide — report as exploratory.\n"
))
cells.append(code(
"def run_lp_iv(data, h, controls, treatment, instrument, outcome):\n"
"    w = data.copy()\n"
"    w['_y'] = w[outcome].shift(-h)\n"
"    for l in range(1,4): w[f'_Ly{l}'] = w[outcome].shift(l)\n"
"    for l in range(1,3): w[f'_Lt{l}'] = w[treatment].shift(l)\n"
"    lags = [f'_Ly{l}' for l in range(1,4)] + [f'_Lt{l}' for l in range(1,3)]\n"
"    need = ['_y', instrument, treatment] + lags + controls\n"
"    sub = w[[c for c in need if c in w.columns]].replace([np.inf,-np.inf],np.nan).dropna()\n"
"    if len(sub) < 30: return None, None, 0\n"
"    cl = _prune(sub, lags + controls)\n"
"    exog = sub[cl].copy(); exog.insert(0,'const',1.0)\n"
"    try:\n"
"        fit = IV2SLS(sub['_y'], exog, sub[[treatment]], sub[[instrument]]).fit(cov_type='kernel')\n"
"        return float(fit.params[treatment]), float(fit.std_errors[treatment]), len(sub)\n"
"    except: return None, None, 0\n\n"
"HORIZONS = list(range(0, 49))\n\n"
"specs = []\n"
"if 'd2pri' in m.columns: specs.append(('d2pri','Δ²PRI (Saadaoui benchmark)','#2980B9'))\n"
"if 'delta2_cgi' in m.columns: specs.append(('delta2_cgi','Δ²CGI (constructed)','#C0392B'))\n\n"
"all_irfs = {}\n"
"for instr, label, color in specs:\n"
"    print(f'Running LP-IV: {label}...', end=' ', flush=True)\n"
"    irf = {'h':[],'coef':[],'se':[]}\n"
"    for h in HORIZONS:\n"
"        c, se, n = run_lp_iv(m, h, CONTROLS, 'lpri', instr, 'lwti')\n"
"        if c is not None:\n"
"            irf['h'].append(h); irf['coef'].append(c); irf['se'].append(se)\n"
"    n_sig = sum(1 for c,se in zip(irf['coef'],irf['se']) if se>0 and abs(c/se)>1.645)\n"
"    all_irfs[label] = (irf, color)\n"
"    print(f'{n_sig}/{len(irf[\"h\"])} horizons significant at 10%')\n\n"
"# Plot\n"
"fig, ax = plt.subplots(figsize=(12, 5))\n"
"z90 = 1.645\n"
"for label, (irf, color) in all_irfs.items():\n"
"    hs = np.array(irf['h']); cs = np.array(irf['coef']); ses = np.array(irf['se'])\n"
"    lw = 2.5 if 'Saadaoui' in label else 1.8\n"
"    ax.plot(hs, cs, color=color, lw=lw, label=label)\n"
"    ax.fill_between(hs, cs-z90*ses, cs+z90*ses, alpha=0.10, color=color)\n"
"ax.axhline(0, color='black', lw=0.8)\n"
"ax.set_xlabel('Horizon h (months)')\n"
"ax.set_ylabel('Causal effect on log WTI')\n"
"ax.set_title('LP-IV Comparison: Δ²CGI vs Δ²PRI\\n'\n"
"             'Convergence = causal channel robust to measurement', fontweight='bold', fontsize=9)\n"
"ax.legend(fontsize=9)\n"
"plt.tight_layout()\n"
"plt.savefig(OUT_DIAG / 'irf_cgi_vs_pri.png', dpi=150, bbox_inches='tight')\n"
"plt.show()\n"
"print('Saved: irf_cgi_vs_pri.png')\n\n"
"# Table at key horizons\n"
"print()\n"
"print('LP-IV AT KEY HORIZONS:')\n"
"print(f'{\"h\":>4}' + ''.join(f'{l[:20]:>25}' for l,(_,__) in all_irfs.items()))\n"
"print('-'*60)\n"
"for h in [0,3,6,12,18,24,36,48]:\n"
"    row = f'{h:>4}'\n"
"    for label,(irf,_) in all_irfs.items():\n"
"        if h in irf['h']:\n"
"            idx = irf['h'].index(h)\n"
"            c,se = irf['coef'][idx], irf['se'][idx]\n"
"            star = '*' if se>0 and abs(c/se)>1.645 else ' '\n"
"            row += f'{c:>+.4f}({se:.4f}){star}'.center(25)\n"
"        else: row += 'n/a'.center(25)\n"
"    print(row)\n\n"
"rows=[]\n"
"for label,(irf,_) in all_irfs.items():\n"
"    for h,c,se in zip(irf['h'],irf['coef'],irf['se']):\n"
"        rows.append({'h':h,'instrument':label,'coef':c,'se':se})\n"
"pd.DataFrame(rows).to_csv(OUT_DIAG/'irf_comparison.csv',index=False)\n"
"print('Saved: irf_comparison.csv')\n"
))

cells.append(md(
"## Cell 9 — Save merged master panel\n\n"
"Save the full merged dataset (df_extended + composite GPR) as the input for the next notebook.\n"
))
cells.append(code(
"m.to_csv(OUT_DIAG / 'master_panel_with_gpr.csv')\n"
"print(f'Saved: master_panel_with_gpr.csv ({m.shape})')\n"
"print()\n"
"print('SUMMARY')\n"
"print('='*60)\n"
"print(f'  Composite GPR: {m[\"composite_gpr\"].notna().sum()}/{len(m)} months')\n"
"print(f'  Δ²CGI:         {m[\"delta2_cgi\"].notna().sum()}/{len(m)} months')\n"
"print()\n"
"f_cgi = f_results.get('delta2_cgi',{}).get('f', 0)\n"
"f_pri = f_results.get('d2pri',{}).get('f', 0)\n"
"print(f'  First-stage F (Δ²PRI):  {f_pri:.2f}')\n"
"print(f'  First-stage F (Δ²CGI): {f_cgi:.2f}')\n"
"print()\n"
"if f_cgi >= 10:\n"
"    print('NEXT NOTEBOOK: 04_dml_and_estimation.ipynb')\n"
"    print('  → Run DML with BOTH d2pri and delta2_cgi as instruments')\n"
"    print('  → Compare IRFs: agreement = measurement robustness finding')\n"
"else:\n"
"    print('NEXT NOTEBOOK: 04_dml_and_estimation.ipynb')\n"
"    print('  → Use d2pri as primary instrument')\n"
"    print('  → Add composite_gpr and sentiment_score_z as DML nuisance controls')\n"
"    print('  → Test whether adding NLP controls changes the causal estimate')\n"
"    print('  → Document Δ²CGI weakness as honest finding (narrative > automated coding)')\n"
))

nb = {
    'nbformat':4,'nbformat_minor':5,
    'metadata':{'kernelspec':{'display_name':'Python 3','language':'python','name':'python3'},
                'language_info':{'name':'python','version':'3.10.0'}},
    'cells': cells
}

errors = []
for i,c in enumerate(nb['cells']):
    if c['cell_type']!='code': continue
    try: ast.parse(''.join(c['source']))
    except SyntaxError as e: errors.append((i,str(e)))

out='../03_instrument_diagnostics_and_macro_merge.ipynb'
with open(out,'w') as f: json.dump(nb,f,indent=1)
print(f'Cells: {len(cells)} | Syntax: {errors if errors else "none"}')
print(f'Size: {os.path.getsize(out):,} bytes')